<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AiCodeReview.Domain\AiCodeReview.Domain.csproj" />
    <ProjectReference Include="..\..\src\AiCodeReview.Application\AiCodeReview.Application.csproj" />
    <ProjectReference Include="..\..\src\AiCodeReview.Infrastructure\AiCodeReview.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
