// <auto-generated />
using System;
using AiCodeReview.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiCodeReview.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiCodeReview.Domain.Ai.AiUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CachedInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_input_tokens");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("estimated_cost_usd");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<Guid>("ReviewRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_run_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_ai_usages");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_ai_usages_created_at_utc");

                    b.HasIndex("ReviewRunId")
                        .HasDatabaseName("ix_ai_usages_review_run_id");

                    b.ToTable("ai_usages", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.Identity.GitHubAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AccessTokenProtected")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_protected");

                    b.Property<DateTimeOffset>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("RefreshTokenProtected")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_protected");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<DateTimeOffset?>("TokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_github_accounts");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_github_accounts_user_id");

                    b.ToTable("github_accounts", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<long>("GitHubUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_user_id");

                    b.Property<DateTimeOffset?>("LastSignedInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_signed_in_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("GitHubUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_github_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.Jobs.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_background_jobs");

                    b.HasIndex("AvailableAtUtc")
                        .HasDatabaseName("ix_background_jobs_claimable")
                        .HasFilter("state = 'Pending'");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("ix_background_jobs_expiring_leases")
                        .HasFilter("state = 'Running'");

                    b.ToTable("background_jobs", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.PullRequests.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author_login");

                    b.Property<string>("BaseRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("base_ref");

                    b.Property<string>("BaseSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("base_sha");

                    b.Property<int>("ChangedFiles")
                        .HasColumnType("integer")
                        .HasColumnName("changed_files");

                    b.Property<Guid>("CodeRepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("code_repository_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<long>("GitHubPullRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_pull_request_id");

                    b.Property<DateTimeOffset>("GitHubUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("github_updated_at_utc");

                    b.Property<string>("HeadRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("head_ref");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("head_sha");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_pull_requests");

                    b.HasIndex("CodeRepositoryId", "GitHubUpdatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_pull_requests_code_repository_id_github_updated_at_utc");

                    b.HasIndex("CodeRepositoryId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_pull_requests_code_repository_id_number");

                    b.ToTable("pull_requests", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.PullRequests.PullRequestFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Additions")
                        .HasColumnType("integer")
                        .HasColumnName("additions");

                    b.Property<string>("BlobSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("blob_sha");

                    b.Property<string>("ChangeStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("change_status");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer")
                        .HasColumnName("deletions");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("head_sha");

                    b.Property<bool>("IsBinary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_binary");

                    b.Property<bool>("IsTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_truncated");

                    b.Property<string>("Patch")
                        .HasColumnType("text")
                        .HasColumnName("patch");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<string>("PreviousPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("previous_path");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_request_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_pull_request_files");

                    b.HasIndex("PullRequestId", "HeadSha", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_pull_request_files_pull_request_id_head_sha_path");

                    b.ToTable("pull_request_files", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.Repositories.CodeRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_branch");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<long>("GitHubRepositoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_repository_id");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PrimaryLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_language");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_code_repositories");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_code_repositories_owner_user_id")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("OwnerUserId", "GitHubRepositoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_code_repositories_owner_user_id_github_repository_id");

                    b.ToTable("code_repositories", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.Reviews.ReviewFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<Guid>("CodeRepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("code_repository_id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer")
                        .HasColumnName("end_line");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("file_path");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suppressed");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<Guid>("ReviewRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_run_id");

                    b.Property<string>("RuleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer")
                        .HasColumnName("start_line");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at_utc");

                    b.Property<Guid?>("StatusChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_changed_by_user_id");

                    b.Property<string>("SuggestedFix")
                        .HasColumnType("text")
                        .HasColumnName("suggested_fix");

                    b.Property<string>("SuppressionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suppression_reason");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_review_findings");

                    b.HasIndex("StatusChangedByUserId")
                        .HasDatabaseName("ix_review_findings_status_changed_by_user_id");

                    b.HasIndex("CodeRepositoryId", "Fingerprint")
                        .HasDatabaseName("ix_review_findings_code_repository_id_fingerprint");

                    b.HasIndex("ReviewRunId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_review_findings_review_run_id_fingerprint");

                    b.HasIndex("CodeRepositoryId", "Severity", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_review_findings_code_repository_id_severity_created_at_utc");

                    b.ToTable("review_findings", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.Reviews.ReviewRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CodeRepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("code_repository_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("head_sha");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_request_id");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("RiskBand")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("risk_band");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("ScoreBreakdownJson")
                        .HasColumnType("text")
                        .HasColumnName("score_breakdown_json");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_review_runs");

                    b.HasIndex("CodeRepositoryId")
                        .HasDatabaseName("ix_review_runs_code_repository_id");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_review_runs_requested_by_user_id");

                    b.HasIndex("PullRequestId", "HeadSha")
                        .IsUnique()
                        .HasDatabaseName("ix_review_runs_active_per_commit")
                        .HasFilter("status IN ('Queued', 'Running')");

                    b.HasIndex("PullRequestId", "QueuedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_review_runs_pull_request_id_queued_at_utc");

                    b.ToTable("review_runs", (string)null);
                });

            modelBuilder.Entity("AiCodeReview.Domain.Ai.AiUsage", b =>
                {
                    b.HasOne("AiCodeReview.Domain.Reviews.ReviewRun", null)
                        .WithMany()
                        .HasForeignKey("ReviewRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_usages_review_runs_review_run_id");
                });

            modelBuilder.Entity("AiCodeReview.Domain.Identity.GitHubAccount", b =>
                {
                    b.HasOne("AiCodeReview.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("AiCodeReview.Domain.Identity.GitHubAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_accounts_users_user_id");
                });

            modelBuilder.Entity("AiCodeReview.Domain.PullRequests.PullRequest", b =>
                {
                    b.HasOne("AiCodeReview.Domain.Repositories.CodeRepository", null)
                        .WithMany()
                        .HasForeignKey("CodeRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pull_requests_code_repositories_code_repository_id");
                });

            modelBuilder.Entity("AiCodeReview.Domain.PullRequests.PullRequestFile", b =>
                {
                    b.HasOne("AiCodeReview.Domain.PullRequests.PullRequest", null)
                        .WithMany("Files")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pull_request_files_pull_requests_pull_request_id");
                });

            modelBuilder.Entity("AiCodeReview.Domain.Repositories.CodeRepository", b =>
                {
                    b.HasOne("AiCodeReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_code_repositories_users_owner_user_id");
                });

            modelBuilder.Entity("AiCodeReview.Domain.Reviews.ReviewFinding", b =>
                {
                    b.HasOne("AiCodeReview.Domain.Repositories.CodeRepository", null)
                        .WithMany()
                        .HasForeignKey("CodeRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_findings_code_repositories_code_repository_id");

                    b.HasOne("AiCodeReview.Domain.Reviews.ReviewRun", null)
                        .WithMany("Findings")
                        .HasForeignKey("ReviewRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_findings_review_runs_review_run_id");

                    b.HasOne("AiCodeReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("StatusChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_review_findings_users_status_changed_by_user_id");
                });

            modelBuilder.Entity("AiCodeReview.Domain.Reviews.ReviewRun", b =>
                {
                    b.HasOne("AiCodeReview.Domain.Repositories.CodeRepository", null)
                        .WithMany()
                        .HasForeignKey("CodeRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_runs_code_repositories_code_repository_id");

                    b.HasOne("AiCodeReview.Domain.PullRequests.PullRequest", null)
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_runs_pull_requests_pull_request_id");

                    b.HasOne("AiCodeReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_runs_users_requested_by_user_id");
                });

            modelBuilder.Entity("AiCodeReview.Domain.PullRequests.PullRequest", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AiCodeReview.Domain.Reviews.ReviewRun", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
